---
# tasks file for zabbix

- name: include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: [zabbix]

- name: include repository tasks
  include: repository.yml
  tags: [zabbix]

- name: include os-specific tasks
  include: "{{ ansible_os_family }}.yml"
  tags: [zabbix]

- name: include config tasks
  include: config.yml
  tags: [zabbix]

- name: include service tasks
  include: service.yml
  tags: [zabbix]
