---
# tasks file for zabbix

- name: include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: [zabbix]

- name: include repository tasks
  include: repository.yml
  tags: [zabbix]

- name: include debian specific tasks
  include: Debian.yml
  when: ansible_os_family=='Debian'
  tags: [zabbix]

- name: include rhel specific tasks
  include: RedHat.yml
  when: ansible_os_family=='RedHat'
  tags: [zabbix]

- name: include config tasks
  include: config.yml
  tags: [zabbix]

- name: include service tasks
  include: service.yml
  tags: [zabbix]
