---
# task file for configurate repository

- name: download release package
  get_url:
    url: "{{ url_package_release }}"
    dest: /tmp/zabbix-release.deb
  when: ansible_os_family=='Debian'
  tags: [zabbix, repository]

- name: download release package
  get_url:
    url: "{{ url_package_release }}"
    dest: /tmp/zabbix-release.rpm
  when: ansible_os_family=='RedHat'
  tags: [zabbix, repository]

- name: install repository for debian system
  apt: deb=/tmp/zabbix-release.deb state=present
  when: ansible_os_family=='Debian'
  tags: [zabbix, repository]

- name: install repository for rhel system
  yum: name=/tmp/zabbix-release.rpm state=present
  when: ansible_os_family=='RedHat'
  tags: [zabbix, repository]

#- name: remove repository package for debian system
#  file:
#    path: /tmp/zabbix-release.deb
#    state: absent
#  when: ansible_os_family=='Debian'
#  tags: [zabbix, repository]
#
#- name: remove repository package for rhel system
#  file:
#    path: /tmp/zabbix-release.rpm
#    state: absent
#  when: ansible_os_family=='RedHat'
#  tags: [zabbix, repository]

- name: update packages cache
  apt: update_cache=yes
  when: ansible_os_family=='Debian'
  tags: [zabbix, repository]
