---
# handlers file for zabbix

- name: restart zabbix-agent
  service: name={{ zabbix_agent_service }} state=restarted

- name: restart zabbix-server
  service: name={{ zabbix_server_service }} state=restarted
